<?php

########################################################################
# Extension Manager/Repository config file for ext: "sourcero"
#
# Auto generated by Extension Builder 2013-02-01
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Sourcero',
	'description' => '',
	'category' => 'module',
	'author' => 'Andreas Thurnheer-Meier, Daniel Corn',
	'author_email' => 'tma@iresults.li, cod@iresults.li',
	'author_company' => 'iresults, iresults',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.5',
			'fluid' => '1.5',
			'typo3' => '4.7',
			'cundd_composer' => '1.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>